// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQ4bsXRdkjWcnio4MQSk0ICqdcWIUFOg',
    appId: '1:255312677677:web:3aba30257684268187a1a4',
    messagingSenderId: '255312677677',
    projectId: 'authtest-matt',
    authDomain: 'authtest-matt.firebaseapp.com',
    storageBucket: 'authtest-matt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVUMUE7ZYXMKQ2tLyTvj2hi3VrLW-P60',
    appId: '1:255312677677:android:77e84501a6b9ec7b87a1a4',
    messagingSenderId: '255312677677',
    projectId: 'authtest-matt',
    storageBucket: 'authtest-matt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsYR1xcUK-c94eACzfUEPyNQATCGJP964',
    appId: '1:255312677677:ios:d13a0b48b33bdcc287a1a4',
    messagingSenderId: '255312677677',
    projectId: 'authtest-matt',
    storageBucket: 'authtest-matt.appspot.com',
    iosClientId: '255312677677-dv0og83el7o95l4skqcpdfg945ke8u61.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationAuthtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsYR1xcUK-c94eACzfUEPyNQATCGJP964',
    appId: '1:255312677677:ios:d13a0b48b33bdcc287a1a4',
    messagingSenderId: '255312677677',
    projectId: 'authtest-matt',
    storageBucket: 'authtest-matt.appspot.com',
    iosClientId: '255312677677-dv0og83el7o95l4skqcpdfg945ke8u61.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationAuthtest',
  );
}
